version: '3'

networks:
  default:
    driver: bridge

services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 2philaEshop5
      MYSQL_DATABASE: opencart
    volumes:
      - ./sql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    restart: always
  
  php:
    build:
      context: ./php-img
    volumes:
      - ./www:/var/www/
      - ./php-img/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    restart: always

  composer:
    restart: 'no'
    image: composer/composer
    command: install
    volumes:
      - ./www/html/opencart:/app/
  
  web:
    image: nginx
    ports:
      - "8080:80"
    depends_on:
      - "mariadb"
      - "php"
    volumes:
      - ./www:/var/www/
      - ./sites:/etc/nginx/conf.d
